{% set version = "1.1.3" %}

package:
  name: thinkx
  version:"{{ version }}

source:
  url: https://pypi.io/packages/source/t/thinkx/thinkx-{{ version }}.tar.gz
  sha256: 1842dede9a25168d61d358bdcab611a5be5e3cff43cbb4704810e53a7fae3988

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib
    - numpy
    - pandas
    - scipy
    - markdown

test:
  imports:
    - thinkbayes  # [not py3k]
    - thinkbayes2
    - thinkdsp
    - thinkplot
    - thinkstats2

about:
  home: http://github.com/AllenDowney/ThinkX
  # the package is MIT but there is no license file upstream, many of the .py files are GPL-3.0 though
  license: MIT
  summary: 'Modules supporting books by Allen Downey'

extra:
  recipe-maintainers:
    - koverholt
