{% set version = "1.1.3" %}

package:
  name: thinkx
  version: "{{ version }}"

source:
  fn: thinkx-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/thinkx/thinkx-{{ version }}.tar.gz
  md5: ecf670a73b753adc6be255b1799fa3c2

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - numpy
    - pandas
    - scipy
    - markdown

test:
  imports:
    - thinkbayes  # [not py3k]
    - thinkbayes2
    - thinkdsp
    - thinkplot
    - thinkstats2

about:
  home: http://github.com/AllenDowney/ThinkX
  license: MIT
  summary: 'Modules supporting books by Allen Downey'

extra:
  recipe-maintainers:
    - koverholt
