travis:
  secure:
    BINSTAR_TOKEN: NrW4o1kx/p13r3L4U1l3YX3XsFdvfblhWiSvaPtM9E+dZ63vY88cYxATDAZS71kT+kZEhh5N4Rxm5MMfG8ooPJzcx4h350a9X+yYkBRDuZdk8AJ6PXyJQd/N3T4OJadZi0LA82q/a8LZbIwkNKoOMSfC23PQb+afB+hXRCk3YLhTIm2N3DIJzXozlv0NcSvUIbfQTd2AAYrocgumJhOZ+beyUR46kWi1oFuEbKpMFLhCuq3FQMf0jSejYBqySA8A+tBuuK5+bgQYI1wlfzFOLxbHc81tM4L3a2QMHSK0ztL2oUnMC0CyaBg7SGOsWEtZHl4svw3SQLa5nb27+qg8V43lZRoPwB7wYk7hi2tdCG1JynIbZwcpcKilB5/IRVVhZRRL+vsT/SRSTLQEmd/b9Hx0nvEY7oUlnl1FsiYDrKO25SbMYmC41S1wlhr0bsGYhLpmjpl2osIQTKLkDGJjcNDy7wybsJ6S3A2NofCD0REqNvCXzKB+jxHGoFv+r+unEXDyEh5lp52h+DUNOs/L+Yj4O7k9e32pe3pb1zoyGG+61r5jFBO2IoKf46Qt7b1hNnEo1JfhXZo89XT99v6wU5H3e2DTqRmiv15CRfs+TGjI4/5dAD1bUGv5wE5yLqmGWpDY8Q+szz47KbtP4M9/CKtZc9o6pe4osG+frRyQZic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
