appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EYn2PQ6GubQwJPMdvPTtgean4drHyIikevL6rStLZ37ap83maP5/SRf/QW16JOEdzOBJly41n6Hhvdyt4NYi7bn82ZZQdWFj1kxcbOLjLJc87HNVouzhwnRXg5a5ZTFatxCbe16IzCLuMzitwS3fguPXlcklxssF6lmZqPy+NbuRG5FzmNasXdvcFpcOGSuVSsgWF8sT0EtS3IkORmzgUzvOKAAHLaYZRdSrjLg6B5EaiZvrp7QG4XhCVKJ0lYrX72J0j4U2pTwh9leyKs0DniYYiXzxyvQGL/cSSh5aV46suEpHGQZjsuW1RGHW9Lg5Pm36fLV+dbV20PMF7H9ooSQUrjlsdp3K9Vtc5yrMmhn+EcoK00LLHAXqEu4pCeWFhVAXV4PyRX+gsfPag13hCta1EyNnUJQtMQ5Sdn9BYTSV9K0BWLHJwuWnOHWtDcIoG5oFOWasd87NwshyuyFDh/bH1avgfMFel26TVTmUa5N7lHKenRbcQho4tWmDN8vO5PL+NU226oLrGKj6raHAzdzfoBlyesKSNN0hCHIAPOp52RFzXwU3gRwxa2HYPJDE7595dHlGo9dUAqFxK6uH9ht9rE55VT0woEcYG4OkpN+JctZJcIRI95HvAUuYslaeojNdPNGSQhyVQC4jmhEq3MAOLM2hiaU9YEl94SWBkt0=}
conda_forge_output_validation: false
